site_name: My Docs
site_url: https://example.com/
nav:
  - Home: index.md
  - API:
    - Utils package: utils.md
    - Config & settings: parameters.md
  - Tutorial:
    - Tuto: ' '
  - About: 
    - License: about/license.md
    - About: about/about.md
theme: readthedocs
