site_name: My Docs
site_url: https://example.com/
nav:
  - Home: index.md
  - API:
    - Utils package: api/utils.md
    - Config & settings: api/parameters.md
  - Tutorial:
    - Tutorial: tutorial/turorial.md
  - About: 
    - License: about/license.md
    - About: about/about.md
theme: readthedocs
